theme: jekyll-theme-minimal

title: <p style="border:4px solid#80d080;"</p><p style="color:#80d080;">Quarantined Bagels</h1></p></a></h1>

description: [Hi.]
logo: /images/logo_heart.jpg
show_downloads: false
google_analytics: [UA-175791564-1]
