<p style="border:4px solid#80d080;"</p>
<p style="color:#80d080;">
title: Quarantined B
description: [Hi.]
logo: /images/logo_heart.jpg
theme: jekyll-theme-minimal
show_downloads: false
google_analytics: [UA-175791564-1]
